export type СhoiceButton = {
	id: number;
	alt: string;
	value: string;
};

export const choiceButtons: СhoiceButton[] = [
	{ id: 1, alt: "Популярные", value: "popular" },
	{ id: 2, alt: "Авторские", value: "authors" },
	{ id: 3, alt: "Походы", value: "hiking" },
	{ id: 4, alt: "Сплавы", value: "rivers" },
	{ id: 5, alt: "Велопрогулки", value: "cycling" },
];

export type СhoiceArticle = {
	id: number;
	title: string;
	price: string;
	image: string;
	alt: string;
	category: string;
};

export const choiceArticles: СhoiceArticle[] = [
	{
		id: 1,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-1.jpg",
		alt: "Машина",
		category: "popular",
	},
	{
		id: 2,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-2.jpg",
		alt: "Пустыня",
		category: "popular",
	},
	{
		id: 3,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-3.jpg",
		alt: "Гора",
		category: "popular",
	},
	{
		id: 4,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-4.jpg",
		alt: "Улица",
		category: "popular",
	},
	{
		id: 5,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-5.jpg",
		alt: "Пляж",
		category: "popular",
	},
	{
		id: 6,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "popular",
	},
	{
		id: 7,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-1.jpg",
		alt: "Машина",
		category: "authors",
	},
	{
		id: 8,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-2.jpg",
		alt: "Пустыня",
		category: "authors",
	},
	{
		id: 9,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-3.jpg",
		alt: "Гора",
		category: "rivers",
	},
	{
		id: 10,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-4.jpg",
		alt: "Улица",
		category: "rivers",
	},
	{
		id: 11,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-5.jpg",
		alt: "Пляж",
		category: "rivers",
	},
	{
		id: 12,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "rivers",
	},
	{
		id: 13,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-1.jpg",
		alt: "Машина",
		category: "rivers",
	},
	{
		id: 14,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-2.jpg",
		alt: "Пустыня",
		category: "cycling",
	},
	{
		id: 15,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-3.jpg",
		alt: "Гора",
		category: "cycling",
	},
	{
		id: 16,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-4.jpg",
		alt: "Улица",
		category: "cycling",
	},
	{
		id: 17,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-5.jpg",
		alt: "Пляж",
		category: "cycling",
	},
	{
		id: 18,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "cycling",
	},
	{
		id: 19,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "cycling",
	},
	{
		id: 20,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "authors",
	},
	{
		id: 21,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-1.jpg",
		alt: "Машина",
		category: "rivers",
	},
	{
		id: 22,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-3.jpg",
		alt: "Гора",
		category: "hiking",
	},
	{
		id: 23,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-4.jpg",
		alt: "Улица",
		category: "hiking",
	},
	{
		id: 24,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-5.jpg",
		alt: "Пляж",
		category: "hiking",
	},
	{
		id: 25,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "hiking",
	},
	{
		id: 26,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "hiking",
	},
	{
		id: 27,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-6.jpg",
		alt: "Пирс",
		category: "hiking",
	},
	{
		id: 28,
		title: "Путешествие в горы",
		price: "80 000",
		image: "/images/choice/card_tour_photo-1.jpg",
		alt: "Машина",
		category: "hiking",
	},
];
