export const galleryData = [
	[
		{id:1,src:"images/Traveling/travel_photo-1.jpg",alt:"Самолет",size:"normal"},
		{id:2,src:"images/Traveling/travel_photo-2.jpg",alt:"Палатка",size:"normal"},
		{id:3,src:"images/Traveling/travel_photo-3.jpg",alt:"Горы",size:"normal"},
		{id:4,src:"images/Traveling/travel_photo-4.jpg",alt:"Дорога",size:"normal"}
	],
	[
		{id:5,src:"images/Traveling/travel_photo-5.jpg",alt:"Дорога",size:"small"},
		{id:6,src:"images/Traveling/travel_photo-6.jpg",alt:"Дорога",size:"small"},
		{id:7,src:"images/Traveling/travel_photo-7.jpg",alt:"Дорога",size:"small"},
		{id:8,src:"images/Traveling/travel_photo-8.jpg",alt:"Дорога",size:"small"},
		{id:9,src:"images/Traveling/travel_photo-9.jpg",alt:"Дорога",size:"small"}
	],
	[
		{id:10,src:"images/Traveling/travel_photo-10.jpg",alt:"Дорога",size:"normal"},
		{id:11,src:"images/Traveling/travel_photo-11.jpg",alt:"Дорога",size:"normal"},
		{id:12,src:"images/Traveling/travel_photo-12.jpg",alt:"Дорога",size:"normal"},
		{id:13,src:"images/Traveling/travel_photo-13.jpg",alt:"Дорога",size:"normal"}
	]
]